### ISSUE TITLE
android 13  Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by zrenjun** [sahooz/country-picker-android#10]
Caused by android.content.res.Resources$NotFoundException
String resource ID #0x0
android.content.res.Resources.getText (Resources.java:512)

android.content.Context.getString (Context.java:766)
com.sahooz.library.countrypicker.Country.load (Country.java:107)

**Comment by sahooz** [comment]
测试未复现。请提供更多信息，包括但不限于语言环境、手机具体品牌型号等等。Country.java:107是获取国家/地区名称，可以断点调试获取哪个国家/地区名称出错更佳
测试机型：红米K40
Android版本：Android 13
语言环境：中文、英文
