### ISSUE TITLE
有两个 locale 值重复的数据

### ISSUE THREAD

**Issue by Alex1990** [sahooz/country-picker-android#5]
文件 [https://github.com/sahooz/country-picker-android/blob/master/countrypicker/src/main/assets/code.json](https://github.com/sahooz/country-picker-android/blob/master/countrypicker/src/main/assets/code.json) 里面有两个 locale 值重复的数据`LC`和`VC`，是为了英文名称不同吗？

**Comment by sahooz** [comment]
不是，纯属没注意。。。  
可能当时抓的网页就也是这样有重复的
