### ISSUE TITLE
英文语言环境下，选择带空格的闪退

### ISSUE THREAD

**Issue by zt80hou** [sahooz/country-picker-android#8]
原因找到了，Country类的toJson()方法中，拼接有误；
1、选择的Antigua and Barbuda，json解析失败，报错原因 org.json.JSONException: Unterminated object at character 81 of {"name":"Antigua and Barbuda", "code":1268, "flag":2131099746, "pinyin":Antigua and Barbuda,"locale":"AG"}
观察发现pinyin字段没有用引号括起来
2、找了好久，对比一下name字段，发现了问题
![01](https://user-images.githubusercontent.com/10629437/153331716-b5ca0f2a-db66-4017-b112-a1123220e74d.png)
图中上面是作者大大的，下面是改正的。
正确代码  "{\"name\":\"" + name + "\", \"code\":" + code + ", \"flag\":" + flag + ", \"pinyin\":\"" + pinyin + "\",\"locale\":\"" + locale + "\"}";

希望作者大大改一下，方便使用。

**Comment by sahooz** [comment]
现在应该好了
